# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-23 15:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wwwapp', '0056_auto_20190719_1851'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workshop',
            options={'permissions': (('see_all_workshops', 'Can see all workshops'), ('edit_all_workshops', 'Can edit all workshops'))},
        ),
    ]
